#include "Floorplanner.hpp"
#include "Utility.hpp"

#include <algorithm>
#include <cmath>
#include <iomanip>
#include <iostream>
#include <limits>
#include <numeric>
#include <random>
#include <string>
#include <vector>

using namespace std;

namespace {

    // ============================================================================
    //  Fast routing-gap-aware source-code floorplanner adapter
    // ----------------------------------------------------------------------------
    //  Goal of this version: it must finish quickly and return a legal-ish packed
    //  coordinate floorplan.  No SA inner-loop repacking, no unbounded repair loops.
    //
    //  Flow:
    //    1) Generate a small set of SOFT shapes and block orders.
    //    2) Sweep a bounded set of outline widths.
    //    3) For each width, binary-search height with deterministic bottom-left pack.
    //    4) EDGE blocks are treated as fixed obstacles before movable packing.
    //
    //  Selection is real outline area W*H first; HPWL is only a small tie breaker.
    // ============================================================================

    static constexpr double INF = 1.0e100;
    static constexpr double TINY = 1.0e-9;
    static constexpr unsigned FAST_SEED = 7u;
    static constexpr int FAST_WIDTH_TRIALS = 6;
    static constexpr int FAST_HEIGHT_BISECT = 3; // used only by optional local refinement
    static constexpr int FAST_RANDOM_ORDERS = 2; // base; makeOrders() scales this with block count
    static constexpr int FAST_RANDOM_SHAPES = 0;
    static constexpr double HPWL_TIE_WEIGHT = 0.012;
    static constexpr double CENTER_TIE_WEIGHT = 1.0e-5;
    static constexpr double ROUTE_GAP_TIE_WEIGHT = 0.080;
    static constexpr double ROUTE_DENSITY = 25.0;
    static constexpr double ROUTE_GAP_SAFETY = 1.03;
    static constexpr double ROUTE_GAP_BIAS = 0.50;
    static constexpr double ROUTE_GAP_MAX_ABS = 180.0;
    static constexpr double PORT_WINDOW_SAFETY_FAST = 1.08;
    // Required-gap policy is intentionally used only to generate packing
    // coordinates and to compare candidates already generated by this fast packer.
    // It does NOT add any new SA/annealing cost term or extra inner-loop estimator.
    static constexpr double DIRECT_CHANNEL_SAFETY_FAST = 1.0;
    static constexpr double MIN_DIRECT_GUARD_NETS_FAST = 25.0;
    static constexpr double SLIVER_SNAP_ABS_FAST = 2.0;
    static constexpr double SLIVER_SNAP_RATIO_FAST = 0.08;
    static constexpr double SPLIT_AWARE_MIN_SCALE_FAST = 0.24;
    static constexpr double SPLIT_AWARE_MAX_SCALE_FAST = 0.78;
    static constexpr double ENDPOINT_GUARD_SCALE_FAST = 0.022;
    static constexpr double ENDPOINT_GUARD_CAP_FAST = 18.0;
    static constexpr double PACK_GAP = 1.0e-3;
    static constexpr int FAST_MAX_TOTAL_LAYOUT_CANDIDATES = 6000;
    static constexpr int FAST_COORD_LIMIT_SMALL = 54;
    static constexpr int FAST_COORD_LIMIT_MID = 36;
    static constexpr int FAST_COORD_LIMIT_LARGE = 24;

    // Phase-1 packing deliberately uses a looser required-gap rule so area search
    // does not get trapped by over-reserved channels.  A bounded DSU-style post pass
    // then compacts the chosen legal floorplan and accepts only if routing-gap proxy
    // and HPWL do not degrade too much.
    static constexpr bool ENABLE_DSU_POST_COMPACTION = true;
    static constexpr double DSU_MAX_AREA_SHRINK = 0.135;
    static constexpr double DSU_DEADSPACE_START = 0.045;
    static constexpr double DSU_ROUTE_GUARD_RATIO = 1.10;
    static constexpr double DSU_HPWL_GUARD_RATIO = 1.10;
    // DSU must be a safe post-compaction.  It may reclaim deadspace, but it should
    // not destroy the route-gap/port-window structure selected by phase-1 packing.
    static constexpr double DSU_GAP_GUARD_RATIO = 1.12;
    static constexpr double DSU_PORT_GUARD_RATIO = 2.00;
    static constexpr double DSU_MIN_AREA_GAIN_IF_ROUTE_WORSE = 0.012;
    static constexpr double DSU_TINY_AREA_GAIN = 0.004;
    static constexpr double DSU_MAX_PORT_MISS_INCREASE = 2.00;
    static constexpr double DSU_MAX_GAP_MISS_INCREASE = 3.00;
    static constexpr int DSU_MAX_VIOLPAIR_INCREASE = 1;
    static constexpr int DSU_MAX_PASSES = 18;
    static constexpr bool FAST_VERBOSE_LOG = true;


    static double sqr(double x) { return x * x; }

    static double clampD(double v, double lo, double hi) {
        if (hi < lo) return lo;
        if (v < lo) return lo;
        if (v > hi) return hi;
        return v;
    }

    static string upperAscii(string s) {
        transform(s.begin(), s.end(), s.begin(), [](unsigned char c) {
            return static_cast<char>(toupper(c));
            });
        return s;
    }

    static double ovLen(double a1, double a2, double b1, double b2) {
        return max(0.0, min(a2, b2) - max(a1, b1));
    }

    static double ovArea(const Rect& a, const Rect& b) {
        return ovLen(a.x, rectRight(a), b.x, rectRight(b)) *
            ovLen(a.y, rectTop(a), b.y, rectTop(b));
    }

    static bool inside(const Rect& r, double W, double H) {
        return r.x >= -EPS && r.y >= -EPS && rectRight(r) <= W + EPS && rectTop(r) <= H + EPS;
    }

    static bool isMovableBlock(const BlockSpec& s) {
        return s.type != BlockType::EDGE;
    }

    static double aspectMid(const BlockSpec& s) {
        double amin = max(0.05, s.aspectMin);
        double amax = max(amin, s.aspectMax);
        return sqrt(amin * amax);
    }

    static double blockNominalArea(const BlockSpec& s) {
        return s.hasFixedSize ? max(1.0, s.fixedW * s.fixedH) : max(1.0, s.area);
    }

    static double totalNominalArea(const Design& design) {
        double a = 0.0;
        for (const auto& s : design.blockSpecs) a += blockNominalArea(s);
        return max(1.0, a);
    }

    static Rect makeShape(const BlockSpec& s, double ratio) {
        Rect r;
        r.x = r.y = 0.0;
        if (s.hasFixedSize) {
            r.w = s.fixedW;
            r.h = s.fixedH;
            return r;
        }
        double amin = max(0.05, s.aspectMin);
        double amax = max(amin, s.aspectMax);
        ratio = clampD(ratio > 0.0 ? ratio : aspectMid(s), amin, amax);
        double area = max(1.0, s.area);
        r.w = sqrt(area * ratio);
        r.h = area / max(TINY, r.w);
        return r;
    }

    static int totalConnBetween(const Design& design, int a, int b) {
        int n = 0;
        if (a >= 0 && b >= 0 && a < static_cast<int>(design.connMatrix.size()) &&
            b < static_cast<int>(design.connMatrix[a].size())) {
            n += max(0, design.connMatrix[a][b]);
        }
        if (a >= 0 && b >= 0 && b < static_cast<int>(design.connMatrix.size()) &&
            a < static_cast<int>(design.connMatrix[b].size())) {
            n += max(0, design.connMatrix[b][a]);
        }
        return n;
    }

    static double endpointDemand(const Design& design, int id) {
        if (id < 0 || id >= static_cast<int>(design.blockSpecs.size())) return 0.0;
        double s = 0.0;
        if (!design.connections.empty()) {
            for (const auto& c : design.connections) {
                if (c.src == id || c.dst == id) s += max(0, c.netCount);
            }
            return s;
        }
        for (int j = 0; j < static_cast<int>(design.blockSpecs.size()); ++j) {
            if (j == id) continue;
            s += totalConnBetween(design, id, j);
        }
        return s;
    }

    static double requiredForNets(const Design& design, int nets) {
        if (nets <= 0) return PACK_GAP;
        // Raw physical lower bound from the problem rule: 25 nets / um.
        // This helper is the full direct-bundle value.  Pair-aware requiredX/YGap()
        // below may use a split-aware fraction of it because Q&A allows net splitting.
        double req = static_cast<double>(nets) / ROUTE_DENSITY + DIRECT_CHANNEL_SAFETY_FAST;
        req = req * ROUTE_GAP_SAFETY + ROUTE_GAP_BIAS;
        double cap = max(25.0, min(ROUTE_GAP_MAX_ABS, 0.10 * min(design.maxOutlineW, design.maxOutlineH)));
        return clampD(req, PACK_GAP, cap);
    }

    static double maxSingleNetRequired(const Design& design) {
        double req = 1.0;
        if (!design.connections.empty()) {
            for (const auto& c : design.connections) req = max(req, requiredForNets(design, max(0, c.netCount)));
            return req;
        }
        const int n = static_cast<int>(design.blockSpecs.size());
        for (int i = 0; i < n; ++i) {
            for (int j = i + 1; j < n; ++j) req = max(req, requiredForNets(design, totalConnBetween(design, i, j)));
        }
        return req;
    }

    static double sliverSnapThresholdFast(const Design& design) {
        // Imported from the reference sourcecode idea: tiny whitespace should not be
        // treated as a routable channel.  Here it is only a minimum coordinate gap for
        // connected pairs, not a new cost.
        return max(SLIVER_SNAP_ABS_FAST, maxSingleNetRequired(design) * SLIVER_SNAP_RATIO_FAST);
    }

    static double blockRoutingRigidity(const Design& design, int id) {
        if (id < 0 || id >= static_cast<int>(design.blockSpecs.size())) return 1.0;
        const BlockSpec& s = design.blockSpecs[id];
        if (s.type == BlockType::EDGE) return 1.18; // fixed boundary + no feedthrough
        if (s.type == BlockType::HARD) return 1.08; // no feedthrough
        if (s.type == BlockType::SOFT) return 0.88; // may absorb some traffic by FT
        return 1.0;
    }

    static double splitAwarePairScale(const Design& design, int a, int b, int nets) {
        if (nets <= 0) return 0.0;
        const double ea = endpointDemand(design, a);
        const double eb = endpointDemand(design, b);
        const double denom = max(1.0, min(ea, eb));
        const double pairShare = clampD(static_cast<double>(nets) / denom, 0.0, 1.0);

        // If this pair is most of both endpoints' demand, keep almost full direct
        // capacity.  If it is only one of many bundles, reserve a fraction and let
        // later routing/path splitting distribute it.
        double scale = SPLIT_AWARE_MIN_SCALE_FAST +
            (SPLIT_AWARE_MAX_SCALE_FAST - SPLIT_AWARE_MIN_SCALE_FAST) * sqrt(pairShare);

        // Hard/edge endpoints have fewer routing choices, so do not shrink their gap
        // as aggressively as soft-soft pairs.
        scale *= sqrt(blockRoutingRigidity(design, a) * blockRoutingRigidity(design, b));
        return clampD(scale, 0.20, 0.86);
    }

    static double requiredPairGap(const Design& design, int a, int b, bool xGap) {
        (void)xGap; // currently symmetric; kept as a hook for future directional tuning.
        const int nets = totalConnBetween(design, a, b);
        if (nets <= 0) return PACK_GAP;

        const double fullDirect = requiredForNets(design, nets);
        double req = fullDirect * splitAwarePairScale(design, a, b, nets);

        // Endpoint pressure from the sourcecode's port-window idea: even a modest
        // pair should not be packed with a numerical zero gap if both endpoints are
        // high-demand blocks.  Keep this bounded so it does not become a hidden cost.
        const double ep = min(endpointDemand(design, a), endpointDemand(design, b));
        const double endpointGuard = min(ENDPOINT_GUARD_CAP_FAST, ENDPOINT_GUARD_SCALE_FAST * ep / ROUTE_DENSITY);
        req = max(req, endpointGuard);

        // Avoid creating 0.x / 1.x um channel strips for connected blocks.  The cap
        // prevents one huge bundle from forcing every candidate to waste outline area.
        req = max(req, min(7.0, sliverSnapThresholdFast(design) * 0.70));

        const double ea = endpointDemand(design, a);
        const double eb = endpointDemand(design, b);
        const double share = clampD(static_cast<double>(nets) / max(1.0, min(ea, eb)), 0.0, 1.0);
        double capFrac = 0.032 + 0.043 * sqrt(share);
        capFrac *= sqrt(blockRoutingRigidity(design, a) * blockRoutingRigidity(design, b));
        const double cap = max(20.0, min(ROUTE_GAP_MAX_ABS, capFrac * min(design.maxOutlineW, design.maxOutlineH)));
        return clampD(req, PACK_GAP, cap);
    }

    static double requiredXGap(const Design& design, int a, int b) {
        return requiredPairGap(design, a, b, true);
    }

    static double requiredYGap(const Design& design, int a, int b) {
        return requiredPairGap(design, a, b, false);
    }

    static double requiredPortOverlap(const Design& design, int a, int b) {
        int nets = totalConnBetween(design, a, b);
        if (nets <= 0) return 0.0;
        return static_cast<double>(nets) / ROUTE_DENSITY * PORT_WINDOW_SAFETY_FAST;
    }


    static double hpwl(const Design& design, const vector<Rect>& r) {
        double s = 0.0;
        if (!design.connections.empty()) {
            for (const auto& c : design.connections) {
                if (c.src < 0 || c.dst < 0 || c.src >= static_cast<int>(r.size()) || c.dst >= static_cast<int>(r.size())) continue;
                s += static_cast<double>(max(0, c.netCount)) *
                    (fabs(rectCx(r[c.src]) - rectCx(r[c.dst])) + fabs(rectCy(r[c.src]) - rectCy(r[c.dst])));
            }
            return s;
        }
        int n = min(static_cast<int>(r.size()), static_cast<int>(design.connMatrix.size()));
        for (int i = 0; i < n; ++i) {
            for (int j = i + 1; j < n; ++j) {
                int nets = totalConnBetween(design, i, j);
                if (nets <= 0) continue;
                s += static_cast<double>(nets) *
                    (fabs(rectCx(r[i]) - rectCx(r[j])) + fabs(rectCy(r[i]) - rectCy(r[j])));
            }
        }
        return s;
    }

    struct EdgeRule {
        char side = 'B'; // T/B/L/R
        int zone = 0;   // T/B: L,M,R -> 0,1,2. L/R: B,M,T -> 0,1,2.
        bool valid = false;
    };

    static bool containsChar(const string& s, char c) { return s.find(c) != string::npos; }

    static EdgeRule parseRule(const string& raw) {
        EdgeRule r;
        string L = upperAscii(raw);
        if (L.size() >= 2) {
            char a = L[0], b = L[1];
            if (a == 'T' && (b == 'L' || b == 'M' || b == 'R')) { r.side = 'T'; r.zone = (b == 'L') ? 0 : (b == 'M' ? 1 : 2); r.valid = true; return r; }
            if (a == 'B' && (b == 'L' || b == 'M' || b == 'R')) { r.side = 'B'; r.zone = (b == 'L') ? 0 : (b == 'M' ? 1 : 2); r.valid = true; return r; }
            if (a == 'L' && (b == 'B' || b == 'M' || b == 'T')) { r.side = 'L'; r.zone = (b == 'B') ? 0 : (b == 'M' ? 1 : 2); r.valid = true; return r; }
            if (a == 'R' && (b == 'B' || b == 'M' || b == 'T')) { r.side = 'R'; r.zone = (b == 'B') ? 0 : (b == 'M' ? 1 : 2); r.valid = true; return r; }
        }
        if (containsChar(L, 'T')) { r.side = 'T'; r.zone = containsChar(L, 'R') ? 2 : (containsChar(L, 'M') ? 1 : 0); r.valid = true; }
        else if (containsChar(L, 'B')) { r.side = 'B'; r.zone = containsChar(L, 'R') ? 2 : (containsChar(L, 'M') ? 1 : 0); r.valid = true; }
        else if (containsChar(L, 'R')) { r.side = 'R'; r.zone = containsChar(L, 'T') ? 2 : (containsChar(L, 'M') ? 1 : 0); r.valid = true; }
        else if (containsChar(L, 'L')) { r.side = 'L'; r.zone = containsChar(L, 'T') ? 2 : (containsChar(L, 'M') ? 1 : 0); r.valid = true; }
        return r;
    }

    static vector<string> splitLocTokens(const string& s) {
        vector<string> out;
        string cur;
        for (char ch : s) {
            if (ch == ',' || ch == ';' || ch == '/' || ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r') {
                if (!cur.empty()) { out.push_back(cur); cur.clear(); }
            }
            else cur.push_back(ch);
        }
        if (!cur.empty()) out.push_back(cur);
        return out;
    }

    static vector<EdgeRule> edgeRules(const BlockSpec& s) {
        vector<EdgeRule> out;
        if (s.locations.empty()) {
            EdgeRule r = parseRule("BL");
            if (r.valid) out.push_back(r);
            return out;
        }
        for (const string& loc : s.locations) {
            vector<string> toks = splitLocTokens(loc);
            if (toks.empty()) toks.push_back(loc);
            for (const string& t : toks) {
                EdgeRule r = parseRule(t);
                if (r.valid) out.push_back(r);
            }
        }
        if (out.empty()) out.push_back(parseRule("BL"));
        return out;
    }

    static double sideSpan(char side, double W, double H) {
        return (side == 'T' || side == 'B') ? W : H;
    }

    static double sideLen(const Rect& r, char side) {
        return (side == 'T' || side == 'B') ? r.w : r.h;
    }

    static pair<double, double> zoneBounds(const EdgeRule& r, double W, double H) {
        double s = sideSpan(r.side, W, H);
        return { static_cast<double>(r.zone) * s / 3.0, static_cast<double>(r.zone + 1) * s / 3.0 };
    }

    static double zoneCenter(const EdgeRule& r, double W, double H) {
        auto b = zoneBounds(r, W, H);
        return 0.5 * (b.first + b.second);
    }

    static double edgeViolation(const Rect& rc, const BlockSpec& spec, double W, double H) {
        if (spec.type != BlockType::EDGE) return 0.0;
        double best = INF;
        for (const EdgeRule& r : edgeRules(spec)) {
            auto b = zoneBounds(r, W, H);
            double v = 0.0;
            if (r.side == 'T') { v += fabs(rectTop(rc) - H); v += max(0.0, b.first - rc.x); v += max(0.0, rectRight(rc) - b.second); }
            else if (r.side == 'B') { v += fabs(rc.y); v += max(0.0, b.first - rc.x); v += max(0.0, rectRight(rc) - b.second); }
            else if (r.side == 'L') { v += fabs(rc.x); v += max(0.0, b.first - rc.y); v += max(0.0, rectTop(rc) - b.second); }
            else { v += fabs(rectRight(rc) - W); v += max(0.0, b.first - rc.y); v += max(0.0, rectTop(rc) - b.second); }
            best = min(best, v);
        }
        return best >= INF * 0.5 ? 0.0 : best;
    }

    static void setEdgeAxis(Rect& r, const EdgeRule& er, double axis, double W, double H) {
        if (er.side == 'T') { r.x = axis; r.y = H - r.h; }
        else if (er.side == 'B') { r.x = axis; r.y = 0.0; }
        else if (er.side == 'L') { r.x = 0.0; r.y = axis; }
        else { r.x = W - r.w; r.y = axis; }
        r.x = clampD(r.x, 0.0, W - r.w);
        r.y = clampD(r.y, 0.0, H - r.h);
    }

    static bool anyOverlapWith(const Rect& r, const vector<Rect>& placed) {
        for (const Rect& o : placed) {
            if (ovArea(r, o) > EPS) return true;
        }
        return false;
    }

    struct ShapeState {
        vector<double> ratio;
    };

    static vector<Rect> makeShapes(const Design& design, const ShapeState& st) {
        int n = static_cast<int>(design.blockSpecs.size());
        vector<Rect> shapes(n);
        for (int i = 0; i < n; ++i) {
            double ratio = (i < static_cast<int>(st.ratio.size())) ? st.ratio[i] : aspectMid(design.blockSpecs[i]);
            shapes[i] = makeShape(design.blockSpecs[i], ratio);
        }
        return shapes;
    }

    static double partialWire(const Design& design, const vector<Rect>& rects, const vector<char>& placed, int id, const Rect& cand) {
        double s = 0.0;
        if (!design.connections.empty()) {
            for (const auto& c : design.connections) {
                int other = -1;
                if (c.src == id) other = c.dst;
                else if (c.dst == id) other = c.src;
                if (other < 0 || other >= static_cast<int>(rects.size()) || !placed[other]) continue;
                s += static_cast<double>(max(0, c.netCount)) *
                    (fabs(rectCx(cand) - rectCx(rects[other])) + fabs(rectCy(cand) - rectCy(rects[other])));
            }
            return s;
        }
        for (int other = 0; other < static_cast<int>(rects.size()); ++other) {
            if (other == id || !placed[other]) continue;
            int nets = totalConnBetween(design, id, other);
            if (nets <= 0) continue;
            s += static_cast<double>(nets) *
                (fabs(rectCx(cand) - rectCx(rects[other])) + fabs(rectCy(cand) - rectCy(rects[other])));
        }
        return s;
    }

    static void addCoord(vector<double>& v, double x, double lo, double hi) {
        if (x >= lo - EPS && x <= hi + EPS) v.push_back(clampD(x, lo, hi));
    }

    static void pruneCoords(vector<double>& v, int limit) {
        if (static_cast<int>(v.size()) <= limit) return;
        vector<double> out;
        out.reserve(limit + 2);
        out.push_back(v.front());
        const int n = static_cast<int>(v.size());
        for (int k = 1; k + 1 < limit; ++k) {
            int idx = static_cast<int>(llround(static_cast<double>(k) * (n - 1) / max(1, limit - 1)));
            idx = max(0, min(n - 1, idx));
            out.push_back(v[idx]);
        }
        out.push_back(v.back());
        sort(out.begin(), out.end());
        out.erase(unique(out.begin(), out.end(), [](double a, double b) { return fabs(a - b) < 1e-5; }), out.end());
        v.swap(out);
    }


    struct EdgePlacedInfo {
        int id = -1;
        EdgeRule rule;
        double pref = 0.0;
        double len = 0.0;
    };

    static bool placeEdgesFast(
        const Design& design,
        const vector<Rect>& shapes,
        double W,
        double H,
        vector<Rect>& rects,
        vector<Rect>& obstacles,
        bool strictZone
    ) {
        rects = shapes;
        obstacles.clear();
        const int n = static_cast<int>(design.blockSpecs.size());

        vector<EdgePlacedInfo> sideItems[4];
        auto sideIndex = [](char s) { return s == 'T' ? 0 : (s == 'B' ? 1 : (s == 'L' ? 2 : 3)); };

        vector<int> edgeIds;
        for (int i = 0; i < n; ++i) if (design.blockSpecs[i].type == BlockType::EDGE) edgeIds.push_back(i);
        sort(edgeIds.begin(), edgeIds.end(), [&](int a, int b) {
            double aa = shapes[a].w * shapes[a].h;
            double bb = shapes[b].w * shapes[b].h;
            if (fabs(aa - bb) > 1e-6) return aa > bb;
            return a < b;
            });

        for (int id : edgeIds) {
            const Rect& sh = shapes[id];
            vector<EdgeRule> rules = edgeRules(design.blockSpecs[id]);
            EdgeRule best = rules.empty() ? parseRule("BL") : rules.front();
            double bestScore = INF;
            for (const EdgeRule& r : rules) {
                if (!r.valid) continue;
                double span = sideSpan(r.side, W, H);
                double len = sideLen(sh, r.side);
                auto zb = zoneBounds(r, W, H);
                double zoneCap = max(0.0, zb.second - zb.first);
                double zoneOverflow = max(0.0, len - zoneCap);
                double sideOverflow = max(0.0, len - span);
                double score = 1.0e9 * sqr(sideOverflow) + 1.0e6 * sqr(zoneOverflow) + 1.0e-3 * r.zone;
                if (score < bestScore) { bestScore = score; best = r; }
            }
            EdgePlacedInfo it;
            it.id = id;
            it.rule = best;
            it.len = sideLen(sh, best.side);
            it.pref = zoneCenter(best, W, H) - 0.5 * it.len;
            sideItems[sideIndex(best.side)].push_back(it);
        }

        for (int si = 0; si < 4; ++si) {
            auto& items = sideItems[si];
            if (items.empty()) continue;
            char side = items.front().rule.side;
            double span = sideSpan(side, W, H);
            sort(items.begin(), items.end(), [](const EdgePlacedInfo& a, const EdgePlacedInfo& b) {
                if (a.rule.zone != b.rule.zone) return a.rule.zone < b.rule.zone;
                if (fabs(a.pref - b.pref) > 1e-6) return a.pref < b.pref;
                return a.id < b.id;
                });

            // First try strict zone-wise packing.  If a zone overflows, fall back to
            // full-side packing so the program still finishes and returns coordinates.
            bool zoneOK = true;
            for (int z = 0; z < 3; ++z) {
                double total = 0.0;
                int cnt = 0;
                EdgeRule zr;
                zr.side = side; zr.zone = z; zr.valid = true;
                for (const auto& it : items) if (it.rule.zone == z) { total += it.len; ++cnt; }
                total += PACK_GAP * max(0, cnt - 1);
                auto zb = zoneBounds(zr, W, H);
                if (total > zb.second - zb.first + EPS) zoneOK = false;
            }

            if (strictZone && zoneOK) {
                for (int z = 0; z < 3; ++z) {
                    EdgeRule zr; zr.side = side; zr.zone = z; zr.valid = true;
                    auto zb = zoneBounds(zr, W, H);
                    double total = 0.0;
                    int cnt = 0;
                    for (const auto& it : items) if (it.rule.zone == z) { total += it.len; ++cnt; }
                    total += PACK_GAP * max(0, cnt - 1);
                    double pos = clampD(0.5 * (zb.first + zb.second - total), zb.first, zb.second - total);
                    for (const auto& it : items) {
                        if (it.rule.zone != z) continue;
                        setEdgeAxis(rects[it.id], it.rule, pos, W, H);
                        pos += it.len + PACK_GAP;
                    }
                }
            }
            else {
                double total = 0.0;
                for (const auto& it : items) total += it.len;
                total += PACK_GAP * max(0, static_cast<int>(items.size()) - 1);
                double pos = clampD(0.5 * (span - total), 0.0, max(0.0, span - total));
                for (const auto& it : items) {
                    setEdgeAxis(rects[it.id], it.rule, pos, W, H);
                    pos += it.len + PACK_GAP;
                }
            }
        }

        // Bounded corner repair for perpendicular edge overlaps.
        for (int pass = 0; pass < 12; ++pass) {
            bool changed = false;
            for (int ai = 0; ai < static_cast<int>(edgeIds.size()); ++ai) {
                for (int bi = ai + 1; bi < static_cast<int>(edgeIds.size()); ++bi) {
                    int a = edgeIds[ai], b = edgeIds[bi];
                    if (ovArea(rects[a], rects[b]) <= EPS) continue;
                    // Move the smaller edge block along its side away from the conflict.
                    int id = (rects[a].w * rects[a].h <= rects[b].w * rects[b].h) ? a : b;
                    EdgeRule r = edgeRules(design.blockSpecs[id]).empty() ? parseRule("BL") : edgeRules(design.blockSpecs[id]).front();
                    // Use currently selected side by detecting boundary.
                    if (fabs(rects[id].y) <= 1e-5) r.side = 'B';
                    else if (fabs(rectTop(rects[id]) - H) <= 1e-5) r.side = 'T';
                    else if (fabs(rects[id].x) <= 1e-5) r.side = 'L';
                    else r.side = 'R';
                    double span = sideSpan(r.side, W, H);
                    double len = sideLen(rects[id], r.side);
                    double cur = (r.side == 'T' || r.side == 'B') ? rects[id].x : rects[id].y;
                    vector<double> cands = { 0.0, max(0.0, span - len), cur };
                    for (int o : edgeIds) if (o != id) {
                        if (r.side == 'T' || r.side == 'B') {
                            cands.push_back(rects[o].x - rects[id].w - PACK_GAP);
                            cands.push_back(rectRight(rects[o]) + PACK_GAP);
                        }
                        else {
                            cands.push_back(rects[o].y - rects[id].h - PACK_GAP);
                            cands.push_back(rectTop(rects[o]) + PACK_GAP);
                        }
                    }
                    Rect old = rects[id], best = rects[id];
                    double bestOv = INF, bestMove = INF;
                    for (double p : cands) {
                        p = clampD(p, 0.0, max(0.0, span - len));
                        setEdgeAxis(rects[id], r, p, W, H);
                        double ov = 0.0;
                        for (int o : edgeIds) if (o != id) ov += ovArea(rects[id], rects[o]);
                        double mv = fabs(p - cur);
                        if (ov < bestOv - EPS || (fabs(ov - bestOv) <= EPS && mv < bestMove)) {
                            bestOv = ov; bestMove = mv; best = rects[id];
                        }
                    }
                    rects[id] = best;
                    if (bestOv + EPS < ovArea(old, rects[id == a ? b : a])) changed = true;
                }
            }
            if (!changed) break;
        }

        bool ok = true;
        for (int id : edgeIds) {
            if (!inside(rects[id], W, H)) ok = false;
            if (strictZone && edgeViolation(rects[id], design.blockSpecs[id], W, H) > 1.0e-4) ok = false;
            obstacles.push_back(rects[id]);
        }
        return ok || !strictZone;
    }

    struct PlaceKey {
        double top = INF;
        double route = INF;
        double right = INF;
        double y = INF;
        double wire = INF;
        double center = INF;
        double x = INF;
    };

    static bool betterKey(const PlaceKey& a, const PlaceKey& b) {
        if (fabs(a.top - b.top) > 1e-6) return a.top < b.top;
        // Same-height candidates prefer satisfying direct channel / port-window needs.
        if (fabs(a.route - b.route) > 1e-6) return a.route < b.route;
        if (fabs(a.right - b.right) > 1e-6) return a.right < b.right;
        if (fabs(a.y - b.y) > 1e-6) return a.y < b.y;
        if (fabs(a.wire - b.wire) > 1e-6) return a.wire < b.wire;
        if (fabs(a.center - b.center) > 1e-6) return a.center < b.center;
        return a.x < b.x;
    }

    static double routeGapPenaltyForCandidate(
        const Design& design,
        const vector<Rect>& placed,
        const vector<int>& placedIds,
        int id,
        const Rect& cand
    ) {
        double p = 0.0;
        for (int k = 0; k < static_cast<int>(placed.size()); ++k) {
            int oid = (k < static_cast<int>(placedIds.size())) ? placedIds[k] : -1;
            if (oid < 0 || oid == id) continue;
            int nets = totalConnBetween(design, id, oid);
            if (nets <= 0) continue;
            const Rect& o = placed[k];
            const double netsW = max(1.0, static_cast<double>(nets));

            double yOv = ovLen(cand.y, rectTop(cand), o.y, rectTop(o));
            if (yOv > EPS) {
                double xGap = INF;
                if (rectRight(o) <= cand.x + EPS) xGap = max(0.0, cand.x - rectRight(o));
                else if (rectRight(cand) <= o.x + EPS) xGap = max(0.0, o.x - rectRight(cand));
                if (xGap < INF * 0.5) {
                    double reqGap = requiredXGap(design, id, oid);
                    double missGap = max(0.0, reqGap - xGap);
                    double reqPort = requiredPortOverlap(design, id, oid);
                    double missPort = max(0.0, reqPort - yOv);
                    p += netsW * (sqr(missGap) + 0.35 * sqr(missPort));
                }
            }

            double xOv = ovLen(cand.x, rectRight(cand), o.x, rectRight(o));
            if (xOv > EPS) {
                double yGap = INF;
                if (rectTop(o) <= cand.y + EPS) yGap = max(0.0, cand.y - rectTop(o));
                else if (rectTop(cand) <= o.y + EPS) yGap = max(0.0, o.y - rectTop(cand));
                if (yGap < INF * 0.5) {
                    double reqGap = requiredYGap(design, id, oid);
                    double missGap = max(0.0, reqGap - yGap);
                    double reqPort = requiredPortOverlap(design, id, oid);
                    double missPort = max(0.0, reqPort - xOv);
                    p += netsW * (sqr(missGap) + 0.35 * sqr(missPort));
                }
            }
        }
        return p;
    }

    struct RouteGapBreakdown {
        double penalty = 0.0;
        double gapPenalty = 0.0;
        double portPenalty = 0.0;
        double maxGapMiss = 0.0;
        double maxPortMiss = 0.0;
        int connectedPairs = 0;
        int violPairs = 0;
        int xInterfaces = 0;
        int yInterfaces = 0;
    };

    static RouteGapBreakdown routeGapBreakdownGlobal(const Design& design, const vector<Rect>& rects) {
        RouteGapBreakdown rb;
        const int n = static_cast<int>(rects.size());
        for (int i = 0; i < n; ++i) {
            for (int j = i + 1; j < n; ++j) {
                int nets = totalConnBetween(design, i, j);
                if (nets <= 0) continue;
                ++rb.connectedPairs;
                bool pairViol = false;
                const double netsW = max(1.0, static_cast<double>(nets));
                const Rect& a = rects[i];
                const Rect& b = rects[j];

                double yOv = ovLen(a.y, rectTop(a), b.y, rectTop(b));
                if (yOv > EPS) {
                    double xGap = INF;
                    if (rectRight(a) <= b.x + EPS) xGap = max(0.0, b.x - rectRight(a));
                    else if (rectRight(b) <= a.x + EPS) xGap = max(0.0, a.x - rectRight(b));
                    if (xGap < INF * 0.5) {
                        ++rb.xInterfaces;
                        double missGap = max(0.0, requiredXGap(design, i, j) - xGap);
                        double missPort = max(0.0, requiredPortOverlap(design, i, j) - yOv);
                        rb.maxGapMiss = max(rb.maxGapMiss, missGap);
                        rb.maxPortMiss = max(rb.maxPortMiss, missPort);
                        rb.gapPenalty += netsW * sqr(missGap);
                        rb.portPenalty += netsW * 0.35 * sqr(missPort);
                        if (missGap > EPS || missPort > EPS) pairViol = true;
                    }
                }
                double xOv = ovLen(a.x, rectRight(a), b.x, rectRight(b));
                if (xOv > EPS) {
                    double yGap = INF;
                    if (rectTop(a) <= b.y + EPS) yGap = max(0.0, b.y - rectTop(a));
                    else if (rectTop(b) <= a.y + EPS) yGap = max(0.0, a.y - rectTop(b));
                    if (yGap < INF * 0.5) {
                        ++rb.yInterfaces;
                        double missGap = max(0.0, requiredYGap(design, i, j) - yGap);
                        double missPort = max(0.0, requiredPortOverlap(design, i, j) - xOv);
                        rb.maxGapMiss = max(rb.maxGapMiss, missGap);
                        rb.maxPortMiss = max(rb.maxPortMiss, missPort);
                        rb.gapPenalty += netsW * sqr(missGap);
                        rb.portPenalty += netsW * 0.35 * sqr(missPort);
                        if (missGap > EPS || missPort > EPS) pairViol = true;
                    }
                }
                if (pairViol) ++rb.violPairs;
            }
        }
        rb.penalty = rb.gapPenalty + rb.portPenalty;
        return rb;
    }

    static double routeGapPenaltyGlobal(const Design& design, const vector<Rect>& rects) {
        return routeGapBreakdownGlobal(design, rects).penalty;
    }


    static bool packOne(
        const Design& design,
        const vector<int>& order,
        const ShapeState& shapeState,
        double W,
        double H,
        bool strictEdge,
        vector<Rect>& outRects
    ) {
        vector<Rect> shapes = makeShapes(design, shapeState);
        vector<Rect> rects, edgeObstacles;
        if (!placeEdgesFast(design, shapes, W, H, rects, edgeObstacles, strictEdge)) return false;

        vector<Rect> placed;
        vector<int> placedIds;
        vector<char> placedMask(design.blockSpecs.size(), 0);
        for (int i = 0; i < static_cast<int>(design.blockSpecs.size()); ++i) {
            if (design.blockSpecs[i].type == BlockType::EDGE) {
                placed.push_back(rects[i]);
                placedIds.push_back(i);
                placedMask[i] = 1;
            }
        }

        double curTop = 0.0;
        for (const Rect& r : placed) curTop = max(curTop, rectTop(r));

        for (int id : order) {
            if (id < 0 || id >= static_cast<int>(design.blockSpecs.size())) continue;
            if (!isMovableBlock(design.blockSpecs[id])) continue;
            const Rect shape = shapes[id];
            if (shape.w > W + EPS || shape.h > H + EPS) return false;
            double maxX = W - shape.w;
            double maxY = H - shape.h;

            vector<double> xs, ys;
            xs.reserve(4 * placed.size() + 6);
            ys.reserve(4 * placed.size() + 6);
            addCoord(xs, 0.0, 0.0, maxX);
            addCoord(xs, maxX, 0.0, maxX);
            addCoord(ys, 0.0, 0.0, maxY);
            addCoord(ys, maxY, 0.0, maxY);
            for (int pi = 0; pi < static_cast<int>(placed.size()); ++pi) {
                const Rect& o = placed[pi];
                int oid = (pi < static_cast<int>(placedIds.size())) ? placedIds[pi] : -1;
                const double gx = (oid >= 0) ? requiredXGap(design, oid, id) : PACK_GAP;
                const double gy = (oid >= 0) ? requiredYGap(design, oid, id) : PACK_GAP;

                // Normal bottom-left / contour candidates.
                addCoord(xs, o.x, 0.0, maxX);
                addCoord(xs, rectRight(o), 0.0, maxX);
                addCoord(xs, o.x - shape.w, 0.0, maxX);
                addCoord(xs, rectRight(o) - shape.w, 0.0, maxX);
                addCoord(ys, o.y, 0.0, maxY);
                addCoord(ys, rectTop(o), 0.0, maxY);
                addCoord(ys, o.y - shape.h, 0.0, maxY);
                addCoord(ys, rectTop(o) - shape.h, 0.0, maxY);

                // Routing-aware candidates.  These are the explicit requested form:
                //   B.x = A.x + A.w + requiredXGap(A, B)
                // plus the symmetric left/top/bottom versions.
                addCoord(xs, rectRight(o) + gx, 0.0, maxX);
                addCoord(xs, o.x - shape.w - gx, 0.0, maxX);
                addCoord(ys, rectTop(o) + gy, 0.0, maxY);
                addCoord(ys, o.y - shape.h - gy, 0.0, maxY);

                // Port-window / common-edge overlap candidates: if we decide to be
                // horizontally adjacent, align y-projections; if vertically adjacent,
                // align x-projections.
                addCoord(ys, o.y, 0.0, maxY);
                addCoord(ys, rectTop(o) - shape.h, 0.0, maxY);
                addCoord(ys, rectCy(o) - 0.5 * shape.h, 0.0, maxY);
                addCoord(xs, o.x, 0.0, maxX);
                addCoord(xs, rectRight(o) - shape.w, 0.0, maxX);
                addCoord(xs, rectCx(o) - 0.5 * shape.w, 0.0, maxX);
            }
            sort(xs.begin(), xs.end());
            xs.erase(unique(xs.begin(), xs.end(), [](double a, double b) { return fabs(a - b) < 1e-5; }), xs.end());
            sort(ys.begin(), ys.end());
            ys.erase(unique(ys.begin(), ys.end(), [](double a, double b) { return fabs(a - b) < 1e-5; }), ys.end());
            const int coordLimit = (static_cast<int>(design.blockSpecs.size()) <= 15) ? FAST_COORD_LIMIT_SMALL :
                (static_cast<int>(design.blockSpecs.size()) <= 35) ? FAST_COORD_LIMIT_MID :
                FAST_COORD_LIMIT_LARGE;
            pruneCoords(xs, coordLimit);
            pruneCoords(ys, coordLimit);

            bool found = false;
            Rect best = shape;
            PlaceKey bestKey;
            for (double y : ys) {
                for (double x : xs) {
                    Rect cand = shape;
                    cand.x = x;
                    cand.y = y;
                    if (!inside(cand, W, H)) continue;
                    if (anyOverlapWith(cand, placed)) continue;
                    PlaceKey key;
                    key.top = max(curTop, rectTop(cand));
                    key.route = routeGapPenaltyForCandidate(design, placed, placedIds, id, cand);
                    key.right = rectRight(cand);
                    key.y = y;
                    key.wire = partialWire(design, rects, placedMask, id, cand);
                    key.center = fabs(rectCx(cand) - 0.5 * W) + fabs(rectCy(cand) - 0.5 * H);
                    key.x = x;
                    if (!found || betterKey(key, bestKey)) {
                        found = true;
                        bestKey = key;
                        best = cand;
                    }
                }
            }
            if (!found) return false;
            rects[id] = best;
            placed.push_back(best);
            placedIds.push_back(id);
            placedMask[id] = 1;
            curTop = max(curTop, rectTop(best));
        }

        outRects = std::move(rects);
        return true;
    }

    static double overlapAll(const vector<Rect>& r, int& cnt) {
        cnt = 0;
        double a = 0.0;
        for (int i = 0; i < static_cast<int>(r.size()); ++i) {
            for (int j = i + 1; j < static_cast<int>(r.size()); ++j) {
                double ov = ovArea(r[i], r[j]);
                if (ov > EPS) { a += ov; ++cnt; }
            }
        }
        return a;
    }

    struct LayoutResult {
        bool legal = false;
        bool strictEdgeLegal = false;
        double W = INF, H = INF, area = INF, hpwl = INF, score = INF;
        double overlap = 0.0, edgeViol = 0.0, outlineViol = 0.0, routePenalty = 0.0;
        double routeGapPenaltyPart = 0.0;
        double routePortPenaltyPart = 0.0;
        double routeMaxGapMiss = 0.0;
        double routeMaxPortMiss = 0.0;
        int routeConnectedPairs = 0;
        int routeViolPairs = 0;
        int routeXInterfaces = 0;
        int routeYInterfaces = 0;
        vector<Rect> rects;
    };

    static LayoutResult scoreLayout(const Design& design, double W, double H, vector<Rect> rects) {
        LayoutResult r;
        r.W = W;
        r.H = H;
        r.area = W * H;
        r.rects = std::move(rects);
        int cnt = 0;
        r.overlap = overlapAll(r.rects, cnt);
        for (int i = 0; i < static_cast<int>(r.rects.size()); ++i) {
            const Rect& rc = r.rects[i];
            r.outlineViol += max(0.0, -rc.x) + max(0.0, -rc.y) + max(0.0, rectRight(rc) - W) + max(0.0, rectTop(rc) - H);
            r.edgeViol += edgeViolation(rc, design.blockSpecs[i], W, H);
        }
        r.hpwl = hpwl(design, r.rects);
        RouteGapBreakdown rb = routeGapBreakdownGlobal(design, r.rects);
        r.routePenalty = rb.penalty;
        r.routeGapPenaltyPart = rb.gapPenalty;
        r.routePortPenaltyPart = rb.portPenalty;
        r.routeMaxGapMiss = rb.maxGapMiss;
        r.routeMaxPortMiss = rb.maxPortMiss;
        r.routeConnectedPairs = rb.connectedPairs;
        r.routeViolPairs = rb.violPairs;
        r.routeXInterfaces = rb.xInterfaces;
        r.routeYInterfaces = rb.yInterfaces;
        double center = 0.0;
        for (const Rect& rc : r.rects) center += fabs(rectCx(rc) - 0.5 * W) + fabs(rectCy(rc) - 0.5 * H);
        r.strictEdgeLegal = r.edgeViol <= 1e-4;
        r.legal = cnt == 0 && r.overlap <= EPS && r.outlineViol <= EPS && W <= design.maxOutlineW + EPS && H <= design.maxOutlineH + EPS;
        r.score = r.area + HPWL_TIE_WEIGHT * r.hpwl + ROUTE_GAP_TIE_WEIGHT * r.routePenalty + CENTER_TIE_WEIGHT * center;
        if (!r.legal) r.score += 1.0e12 + 1.0e9 * r.overlap + 1.0e10 * r.outlineViol;
        if (!r.strictEdgeLegal) r.score += 1.0e8 * r.edgeViol;
        return r;
    }

    static bool betterLayout(const LayoutResult& a, const LayoutResult& b) {
        if (a.legal != b.legal) return a.legal;
        if (a.strictEdgeLegal != b.strictEdgeLegal) return a.strictEdgeLegal;
        if (a.legal && b.legal) {
            double tol = max(1.0, 0.001 * min(a.area, b.area));
            if (fabs(a.area - b.area) > tol) return a.area < b.area;
            if (fabs(a.routePenalty - b.routePenalty) > max(1.0, 0.02 * min(a.routePenalty, b.routePenalty))) {
                return a.routePenalty < b.routePenalty;
            }
        }
        return a.score < b.score;
    }

    static double minWidthBound(const Design& design, const ShapeState& st) {
        vector<Rect> shapes = makeShapes(design, st);
        double w = 1.0;
        for (const Rect& r : shapes) w = max(w, r.w);
        // EDGE zone feasibility lower bound.
        double needBucket[12] = { 0 };
        for (int i = 0; i < static_cast<int>(design.blockSpecs.size()); ++i) {
            if (design.blockSpecs[i].type != BlockType::EDGE) continue;
            vector<EdgeRule> rs = edgeRules(design.blockSpecs[i]);
            EdgeRule er = rs.empty() ? parseRule("BL") : rs.front();
            int side = (er.side == 'T') ? 0 : (er.side == 'B' ? 1 : (er.side == 'L' ? 2 : 3));
            int bucket = side * 3 + er.zone;
            needBucket[bucket] += sideLen(shapes[i], er.side) + PACK_GAP;
        }
        for (int b = 0; b < 6; ++b) w = max(w, 3.0 * needBucket[b]); // top/bottom buckets
        return min(w, design.maxOutlineW);
    }

    static double minHeightBound(const Design& design, const ShapeState& st) {
        vector<Rect> shapes = makeShapes(design, st);
        double h = 1.0;
        for (const Rect& r : shapes) h = max(h, r.h);
        double needBucket[12] = { 0 };
        for (int i = 0; i < static_cast<int>(design.blockSpecs.size()); ++i) {
            if (design.blockSpecs[i].type != BlockType::EDGE) continue;
            vector<EdgeRule> rs = edgeRules(design.blockSpecs[i]);
            EdgeRule er = rs.empty() ? parseRule("BL") : rs.front();
            int side = (er.side == 'T') ? 0 : (er.side == 'B' ? 1 : (er.side == 'L' ? 2 : 3));
            int bucket = side * 3 + er.zone;
            needBucket[bucket] += sideLen(shapes[i], er.side) + PACK_GAP;
        }
        for (int b = 6; b < 12; ++b) h = max(h, 3.0 * needBucket[b]); // left/right buckets
        return min(h, design.maxOutlineH);
    }

    static vector<int> degreeOrder(const Design& design) {
        int n = static_cast<int>(design.blockSpecs.size());
        vector<int> ids(n);
        iota(ids.begin(), ids.end(), 0);
        vector<int> deg(n, 0);
        if (!design.connections.empty()) {
            for (const auto& c : design.connections) {
                if (c.src >= 0 && c.src < n) deg[c.src] += max(0, c.netCount);
                if (c.dst >= 0 && c.dst < n) deg[c.dst] += max(0, c.netCount);
            }
        }
        else {
            for (int i = 0; i < n; ++i) for (int j = 0; j < n; ++j) deg[i] += totalConnBetween(design, i, j);
        }
        sort(ids.begin(), ids.end(), [&](int a, int b) {
            bool ma = isMovableBlock(design.blockSpecs[a]);
            bool mb = isMovableBlock(design.blockSpecs[b]);
            if (ma != mb) return ma > mb;
            if (deg[a] != deg[b]) return deg[a] > deg[b];
            double aa = blockNominalArea(design.blockSpecs[a]);
            double bb = blockNominalArea(design.blockSpecs[b]);
            if (fabs(aa - bb) > 1e-6) return aa > bb;
            return a < b;
            });
        return ids;
    }

    static vector<vector<int>> makeOrders(const Design& design) {
        int n = static_cast<int>(design.blockSpecs.size());
        vector<int> ids(n);
        iota(ids.begin(), ids.end(), 0);
        vector<vector<int>> orders;

        auto movableFirst = [&](vector<int> v) {
            stable_sort(v.begin(), v.end(), [&](int a, int b) {
                return isMovableBlock(design.blockSpecs[a]) > isMovableBlock(design.blockSpecs[b]);
                });
            return v;
            };

        vector<int> byArea = ids;
        sort(byArea.begin(), byArea.end(), [&](int a, int b) {
            bool ma = isMovableBlock(design.blockSpecs[a]);
            bool mb = isMovableBlock(design.blockSpecs[b]);
            if (ma != mb) return ma > mb;
            double aa = blockNominalArea(design.blockSpecs[a]);
            double bb = blockNominalArea(design.blockSpecs[b]);
            return aa > bb;
            });
        orders.push_back(byArea);

        vector<int> byHeight = ids;
        sort(byHeight.begin(), byHeight.end(), [&](int a, int b) {
            Rect ra = makeShape(design.blockSpecs[a], aspectMid(design.blockSpecs[a]));
            Rect rb = makeShape(design.blockSpecs[b], aspectMid(design.blockSpecs[b]));
            if (isMovableBlock(design.blockSpecs[a]) != isMovableBlock(design.blockSpecs[b])) return isMovableBlock(design.blockSpecs[a]) > isMovableBlock(design.blockSpecs[b]);
            return ra.h > rb.h;
            });
        orders.push_back(byHeight);

        vector<int> byWidth = ids;
        sort(byWidth.begin(), byWidth.end(), [&](int a, int b) {
            Rect ra = makeShape(design.blockSpecs[a], aspectMid(design.blockSpecs[a]));
            Rect rb = makeShape(design.blockSpecs[b], aspectMid(design.blockSpecs[b]));
            if (isMovableBlock(design.blockSpecs[a]) != isMovableBlock(design.blockSpecs[b])) return isMovableBlock(design.blockSpecs[a]) > isMovableBlock(design.blockSpecs[b]);
            return ra.w > rb.w;
            });
        orders.push_back(byWidth);

        vector<int> byDegree = degreeOrder(design);
        orders.push_back(byDegree);
        orders.push_back(movableFirst(ids));

        // Hot-pair perturbation: visit endpoints of high-demand connections together,
        // encouraging common-edge / near-neighbor placement before the remaining blocks.
        vector<pair<int, pair<int, int>>> hotPairs;
        for (int i = 0; i < n; ++i) {
            for (int j = i + 1; j < n; ++j) {
                int nets = totalConnBetween(design, i, j);
                if (nets > 0 && isMovableBlock(design.blockSpecs[i]) && isMovableBlock(design.blockSpecs[j])) {
                    hotPairs.push_back({ nets, {i, j} });
                }
            }
        }
        sort(hotPairs.begin(), hotPairs.end(), [](const auto& a, const auto& b) { return a.first > b.first; });
        vector<int> hotOrder;
        vector<char> used(n, 0);
        for (const auto& hp : hotPairs) {
            int a = hp.second.first, b = hp.second.second;
            if (!used[a]) { hotOrder.push_back(a); used[a] = 1; }
            if (!used[b]) { hotOrder.push_back(b); used[b] = 1; }
        }
        for (int id : byDegree) if (isMovableBlock(design.blockSpecs[id]) && !used[id]) hotOrder.push_back(id);
        for (int id : ids) if (!isMovableBlock(design.blockSpecs[id])) hotOrder.push_back(id);
        if (!hotOrder.empty()) orders.push_back(hotOrder);

        // Greedy net-growth perturbation: after a high-degree seed, repeatedly pick
        // the unplaced block with strongest connection to the placed set.
        vector<int> growOrder;
        used.assign(n, 0);
        int seed = -1;
        for (int id : byDegree) if (isMovableBlock(design.blockSpecs[id])) { seed = id; break; }
        if (seed >= 0) {
            growOrder.push_back(seed); used[seed] = 1;
            while (true) {
                int best = -1, bestConn = -1;
                double bestArea = -1.0;
                for (int id : ids) {
                    if (used[id] || !isMovableBlock(design.blockSpecs[id])) continue;
                    int conn = 0;
                    for (int p : growOrder) conn += totalConnBetween(design, id, p);
                    double area = blockNominalArea(design.blockSpecs[id]);
                    if (conn > bestConn || (conn == bestConn && area > bestArea)) {
                        bestConn = conn; bestArea = area; best = id;
                    }
                }
                if (best < 0) break;
                growOrder.push_back(best); used[best] = 1;
            }
            for (int id : ids) if (!isMovableBlock(design.blockSpecs[id])) growOrder.push_back(id);
            orders.push_back(growOrder);
        }

        // Edge-interface perturbation: blocks connected to EDGE macros are packed
        // early so they can secure inner-side port windows.
        vector<int> edgeFirst = byDegree;
        stable_sort(edgeFirst.begin(), edgeFirst.end(), [&](int a, int b) {
            if (isMovableBlock(design.blockSpecs[a]) != isMovableBlock(design.blockSpecs[b])) return isMovableBlock(design.blockSpecs[a]) > isMovableBlock(design.blockSpecs[b]);
            auto edgeConn = [&](int id) {
                int s = 0;
                for (int e = 0; e < n; ++e) if (design.blockSpecs[e].type == BlockType::EDGE) s += totalConnBetween(design, id, e);
                return s;
                };
            int ea = edgeConn(a), eb = edgeConn(b);
            if (ea != eb) return ea > eb;
            return endpointDemand(design, a) > endpointDemand(design, b);
            });
        orders.push_back(edgeFirst);

        mt19937 rng(FAST_SEED + 31u * static_cast<unsigned>(n));
        vector<int> mov;
        for (int id : ids) if (isMovableBlock(design.blockSpecs[id])) mov.push_back(id);

        // Runtime-bounded diversity: for n blocks we want at least n^2 high-level
        // layout candidates, but we do not want an unbounded number of random orders.
        // Public problem scale is below 50 blocks, so this cap keeps runtime stable.
        const int randomOrderCount = min(36, max(FAST_RANDOM_ORDERS, max(2, n)));
        for (int k = 0; k < randomOrderCount; ++k) {
            vector<int> v = mov;
            if (k % 3 == 0) {
                shuffle(v.begin(), v.end(), rng);
            }
            else {
                // Degree-random perturbation: mostly high-degree first, with stable
                // precomputed jitter so the comparator remains a strict weak ordering.
                vector<double> score(n, 0.0);
                for (int id : v) {
                    double j = uniform_real_distribution<double>(0.0, 1.0)(rng);
                    score[id] = endpointDemand(design, id) * (0.65 + j) + 1e-6 * id;
                }
                sort(v.begin(), v.end(), [&](int a, int b) {
                    if (fabs(score[a] - score[b]) > 1e-9) return score[a] > score[b];
                    return a < b;
                    });
            }
            if (k % 4 == 2) reverse(v.begin(), v.end());
            for (int id : ids) if (!isMovableBlock(design.blockSpecs[id])) v.push_back(id);
            orders.push_back(v);
        }

        // Remove exact duplicates.
        vector<vector<int>> uniqueOrders;
        for (const auto& o : orders) {
            bool dup = false;
            for (const auto& u : uniqueOrders) if (u == o) { dup = true; break; }
            if (!dup) uniqueOrders.push_back(o);
        }
        return uniqueOrders;
    }

    static vector<ShapeState> makeShapeStates(const Design& design) {
        int n = static_cast<int>(design.blockSpecs.size());
        vector<ShapeState> states;
        auto make = [&](int mode) {
            ShapeState st;
            st.ratio.assign(n, 1.0);
            for (int i = 0; i < n; ++i) {
                const BlockSpec& s = design.blockSpecs[i];
                double amin = max(0.05, s.aspectMin);
                double amax = max(amin, s.aspectMax);
                double r = aspectMid(s);
                if (!s.hasFixedSize) {
                    if (mode == 1) r = clampD(1.0, amin, amax);
                    else if (mode == 2) r = amin;
                    else if (mode == 3) r = amax;
                    else if (mode == 4) r = (i % 2 == 0) ? amin : amax;
                    else if (mode == 5) r = (i % 2 == 0) ? amax : amin;
                }
                st.ratio[i] = r;
            }
            return st;
            };
        for (int m = 0; m <= 3; ++m) states.push_back(make(m));

        mt19937 rng(FAST_SEED ^ (0x9e3779b9u + static_cast<unsigned>(n)));
        for (int k = 0; k < FAST_RANDOM_SHAPES; ++k) {
            ShapeState st;
            st.ratio.assign(n, 1.0);
            for (int i = 0; i < n; ++i) {
                const BlockSpec& sp = design.blockSpecs[i];
                double amin = max(0.05, sp.aspectMin);
                double amax = max(amin, sp.aspectMax);
                double r = aspectMid(sp);
                if (!sp.hasFixedSize) {
                    double u = uniform_real_distribution<double>(0.0, 1.0)(rng);
                    // Sample in log-space, with endpoints occasionally emphasized.
                    if (k % 3 == 1 && i % 2 == 0) r = amin;
                    else if (k % 3 == 2 && i % 2 == 1) r = amax;
                    else r = exp(log(amin) * (1.0 - u) + log(amax) * u);
                }
                st.ratio[i] = r;
            }
            states.push_back(st);
        }
        return states;
    }

    static vector<double> makeWidthTrials(const Design& design, const ShapeState& st) {
        vector<double> wv;
        double area = totalNominalArea(design);
        double minW = minWidthBound(design, st);
        double minH = minHeightBound(design, st);
        double aspect = design.maxOutlineW / max(1.0, design.maxOutlineH);
        double base = sqrt(area * aspect);
        double factors[] = { 0.62, 0.70, 0.78, 0.86, 0.94, 1.00, 1.08, 1.16, 1.26, 1.38, 1.52 };
        for (double f : factors) wv.push_back(clampD(base * f, minW, design.maxOutlineW));
        for (int i = 0; i < FAST_WIDTH_TRIALS; ++i) {
            double t = (FAST_WIDTH_TRIALS == 1) ? 0.0 : static_cast<double>(i) / (FAST_WIDTH_TRIALS - 1);
            double curved = t * t;
            wv.push_back(clampD(minW + (design.maxOutlineW - minW) * curved, minW, design.maxOutlineW));
        }
        wv.push_back(design.maxOutlineW);
        wv.push_back(max(minW, area / max(1.0, design.maxOutlineH)));
        sort(wv.begin(), wv.end());
        wv.erase(unique(wv.begin(), wv.end(), [](double a, double b) { return fabs(a - b) < 1.0; }), wv.end());
        (void)minH;
        return wv;
    }

    static vector<double> makeHeightTrials(const Design& design, const ShapeState& st, double W) {
        vector<double> hv;
        const double area = totalNominalArea(design);
        const double minH = clampD(minHeightBound(design, st), 1.0, design.maxOutlineH);
        const double base = clampD(area / max(1.0, W), minH, design.maxOutlineH);

        // Symmetric to makeWidthTrials(), but centered around area/W.  These explicit
        // H candidates replace repeated binary-search packing in the main loop, so
        // each high-level candidate costs one deterministic pack.
        const double factors[] = { 0.70, 0.78, 0.86, 0.94, 1.00, 1.08, 1.18, 1.30, 1.45, 1.62 };
        for (double f : factors) hv.push_back(clampD(base * f, minH, design.maxOutlineH));
        hv.push_back(minH);
        hv.push_back(design.maxOutlineH);
        sort(hv.begin(), hv.end());
        hv.erase(unique(hv.begin(), hv.end(), [](double a, double b) { return fabs(a - b) < 1.0; }), hv.end());
        return hv;
    }

    static bool tryExplicitWH(
        const Design& design,
        const vector<int>& order,
        const ShapeState& st,
        double W,
        double H,
        bool strictEdge,
        LayoutResult& out
    ) {
        if (W > design.maxOutlineW + EPS || H > design.maxOutlineH + EPS) return false;
        if (W < minWidthBound(design, st) - EPS || H < minHeightBound(design, st) - EPS) return false;
        vector<Rect> rects;
        if (!packOne(design, order, st, W, H, strictEdge, rects)) return false;
        out = scoreLayout(design, W, H, std::move(rects));
        return true;
    }

    static bool tryWidthHeight(
        const Design& design,
        const vector<int>& order,
        const ShapeState& st,
        double W,
        bool strictEdge,
        LayoutResult& out
    ) {
        double minH = minHeightBound(design, st);
        minH = clampD(minH, 1.0, design.maxOutlineH);
        vector<Rect> rects;
        if (!packOne(design, order, st, W, design.maxOutlineH, strictEdge, rects)) return false;

        double lo = minH;
        double hi = design.maxOutlineH;
        vector<Rect> bestRects = rects;
        for (int it = 0; it < FAST_HEIGHT_BISECT; ++it) {
            double mid = 0.5 * (lo + hi);
            vector<Rect> trial;
            if (packOne(design, order, st, W, mid, strictEdge, trial)) {
                hi = mid;
                bestRects = std::move(trial);
            }
            else {
                lo = mid;
            }
        }
        // Repack at a small slack above hi for numeric stability.
        double H = min(design.maxOutlineH, hi + 1.0e-3);
        vector<Rect> finalRects;
        if (!packOne(design, order, st, W, H, strictEdge, finalRects)) {
            H = min(design.maxOutlineH, hi + 0.25);
            if (!packOne(design, order, st, W, H, strictEdge, finalRects)) {
                finalRects = bestRects;
            }
        }
        out = scoreLayout(design, W, H, std::move(finalRects));
        return true;
    }

    static LayoutResult fallbackShelf(const Design& design) {
        int n = static_cast<int>(design.blockSpecs.size());
        ShapeState st;
        st.ratio.assign(n, 1.0);
        for (int i = 0; i < n; ++i) st.ratio[i] = aspectMid(design.blockSpecs[i]);
        vector<Rect> shapes = makeShapes(design, st);
        vector<Rect> rects, placed;
        placeEdgesFast(design, shapes, design.maxOutlineW, design.maxOutlineH, rects, placed, false);

        vector<int> order = degreeOrder(design);
        double x = 0.0, y = 0.0, rowH = 0.0;
        for (int id : order) {
            if (!isMovableBlock(design.blockSpecs[id])) continue;
            Rect r = shapes[id];
            if (x + r.w > design.maxOutlineW && x > EPS) {
                x = 0.0;
                y += rowH + PACK_GAP;
                rowH = 0.0;
            }
            r.x = clampD(x, 0.0, max(0.0, design.maxOutlineW - r.w));
            r.y = clampD(y, 0.0, max(0.0, design.maxOutlineH - r.h));
            // If this row conflicts with an EDGE obstacle, slide right/down in a
            // bounded way.  It is fallback only, so keep it simple.
            for (int trial = 0; trial < 80 && anyOverlapWith(r, placed); ++trial) {
                x += 10.0;
                if (x + r.w > design.maxOutlineW) { x = 0.0; y += rowH + 10.0; rowH = 0.0; }
                r.x = clampD(x, 0.0, max(0.0, design.maxOutlineW - r.w));
                r.y = clampD(y, 0.0, max(0.0, design.maxOutlineH - r.h));
            }
            rects[id] = r;
            placed.push_back(r);
            x += r.w + PACK_GAP;
            rowH = max(rowH, r.h);
        }
        return scoreLayout(design, design.maxOutlineW, design.maxOutlineH, std::move(rects));
    }


    static bool layoutPlacementLegal(const LayoutResult& r) {
        return r.legal && r.overlap <= EPS && r.outlineViol <= EPS;
    }

    static bool repackEdgesForLayout(
        const Design& design,
        double W,
        double H,
        bool strictEdge,
        vector<Rect>& rects
    ) {
        vector<Rect> repacked;
        vector<Rect> obstacles;
        if (!placeEdgesFast(design, rects, W, H, repacked, obstacles, strictEdge)) return false;
        rects.swap(repacked);
        return true;
    }

    static void clampMovablesAndRepackEdges(
        const Design& design,
        double W,
        double H,
        bool strictEdge,
        vector<Rect>& rects
    ) {
        for (int i = 0; i < static_cast<int>(rects.size()); ++i) {
            if (!isMovableBlock(design.blockSpecs[i])) continue;
            rects[i].x = clampD(rects[i].x, 0.0, max(0.0, W - rects[i].w));
            rects[i].y = clampD(rects[i].y, 0.0, max(0.0, H - rects[i].h));
        }
        (void)repackEdgesForLayout(design, W, H, strictEdge, rects);
    }

    static void spreadRepairLayout(
        const Design& design,
        double W,
        double H,
        bool strictEdge,
        vector<Rect>& rects,
        int maxPasses
    ) {
        const int n = static_cast<int>(rects.size());
        clampMovablesAndRepackEdges(design, W, H, strictEdge, rects);
        for (int pass = 0; pass < maxPasses; ++pass) {
            bool changed = false;
            for (int i = 0; i < n; ++i) {
                for (int j = i + 1; j < n; ++j) {
                    double ox = ovLen(rects[i].x, rectRight(rects[i]), rects[j].x, rectRight(rects[j]));
                    double oy = ovLen(rects[i].y, rectTop(rects[i]), rects[j].y, rectTop(rects[j]));
                    if (ox <= EPS || oy <= EPS) continue;

                    bool mi = isMovableBlock(design.blockSpecs[i]);
                    bool mj = isMovableBlock(design.blockSpecs[j]);
                    if (!mi && !mj) continue;

                    changed = true;
                    bool pushX = ox <= oy;
                    double px = ox + 1.0;
                    double py = oy + 1.0;
                    if (pushX) {
                        double dir = (rectCx(rects[i]) <= rectCx(rects[j])) ? -1.0 : 1.0;
                        if (mi && mj) {
                            rects[i].x += 0.5 * dir * px;
                            rects[j].x -= 0.5 * dir * px;
                        }
                        else if (mi) {
                            rects[i].x += dir * px;
                        }
                        else if (mj) {
                            rects[j].x -= dir * px;
                        }
                    }
                    else {
                        double dir = (rectCy(rects[i]) <= rectCy(rects[j])) ? -1.0 : 1.0;
                        if (mi && mj) {
                            rects[i].y += 0.5 * dir * py;
                            rects[j].y -= 0.5 * dir * py;
                        }
                        else if (mi) {
                            rects[i].y += dir * py;
                        }
                        else if (mj) {
                            rects[j].y -= dir * py;
                        }
                    }
                    clampMovablesAndRepackEdges(design, W, H, strictEdge, rects);
                }
            }
            if (!changed) break;
        }
    }

    static LayoutResult applyDSUScaleCandidate(
        const Design& design,
        const LayoutResult& base,
        double newW,
        double newH,
        bool compactX,
        bool compactY
    ) {
        vector<Rect> rects = base.rects;
        const double fx = compactX ? (newW / max(1.0, base.W)) : 1.0;
        const double fy = compactY ? (newH / max(1.0, base.H)) : 1.0;

        for (int i = 0; i < static_cast<int>(rects.size()); ++i) {
            if (!isMovableBlock(design.blockSpecs[i])) continue;
            double cx = rectCx(rects[i]);
            double cy = rectCy(rects[i]);
            if (compactX) rects[i].x = cx * fx - 0.5 * rects[i].w;
            if (compactY) rects[i].y = cy * fy - 0.5 * rects[i].h;
        }
        clampMovablesAndRepackEdges(design, newW, newH, base.strictEdgeLegal, rects);
        spreadRepairLayout(design, newW, newH, base.strictEdgeLegal, rects, 22);
        return scoreLayout(design, newW, newH, std::move(rects));
    }

    static bool dsuAcceptable(
        const Design& design,
        const LayoutResult& cand,
        const LayoutResult& anchor,
        double minAllowedArea
    ) {
        (void)design;
        if (!layoutPlacementLegal(cand)) return false;
        if (cand.strictEdgeLegal != anchor.strictEdgeLegal && anchor.strictEdgeLegal) return false;
        if (cand.area + 1.0 < minAllowedArea) return false;
        if (cand.area >= anchor.area - 1.0) return false;

        // DSU is a post-process, not a new cost.  These guards are intentionally
        // stricter than the phase-1 selector: DSU should compact whitespace only when
        // it does not damage route-aware gaps / port windows.
        const double areaGain = (anchor.area - cand.area) / max(1.0, anchor.area);
        const double routeWorse = (cand.routePenalty - anchor.routePenalty) / max(1.0, anchor.routePenalty);

        if (cand.hpwl > anchor.hpwl * DSU_HPWL_GUARD_RATIO + 8000.0) return false;

        if (anchor.routePenalty <= 1.0) {
            if (cand.routePenalty > 5000.0) return false;
        }
        else if (cand.routePenalty > anchor.routePenalty * DSU_ROUTE_GUARD_RATIO + 5000.0) {
            return false;
        }

        // A tiny area win is not worth opening new route-gap violations.  This catches
        // the log case where area improved only ~0.2%, but routeGap/portPart worsened.
        if (routeWorse > 0.03 && areaGain < DSU_MIN_AREA_GAIN_IF_ROUTE_WORSE) return false;
        if (areaGain < DSU_TINY_AREA_GAIN && cand.routePenalty > anchor.routePenalty + 1000.0) return false;

        // Guard the two sub-parts separately.  routePenalty is often dominated by
        // gapPart, so port-window damage can be hidden if only the total is checked.
        if (cand.routeGapPenaltyPart > anchor.routeGapPenaltyPart * DSU_GAP_GUARD_RATIO + 8000.0) return false;
        if (anchor.routePortPenaltyPart <= 1000.0) {
            if (cand.routePortPenaltyPart > max(3500.0, anchor.routePortPenaltyPart + 2500.0)) return false;
        }
        else if (cand.routePortPenaltyPart > anchor.routePortPenaltyPart * DSU_PORT_GUARD_RATIO + 5000.0) {
            return false;
        }

        if (cand.routeMaxPortMiss > anchor.routeMaxPortMiss + DSU_MAX_PORT_MISS_INCREASE) return false;
        if (areaGain < 0.020 && cand.routeMaxGapMiss > anchor.routeMaxGapMiss + DSU_MAX_GAP_MISS_INCREASE) return false;
        if (cand.routeViolPairs > anchor.routeViolPairs + DSU_MAX_VIOLPAIR_INCREASE) return false;

        return true;
    }

    static LayoutResult dsuPostCompaction(const Design& design, const LayoutResult& start) {
        if (!ENABLE_DSU_POST_COMPACTION || !layoutPlacementLegal(start)) return start;

        const double blockArea = totalNominalArea(design);
        const double deadspace = clampD((start.area - blockArea) / max(1.0, start.area), 0.0, 0.95);
        double cap = 0.0;
        if (deadspace > DSU_DEADSPACE_START) cap = 0.50 * (deadspace - DSU_DEADSPACE_START);
        cap = clampD(cap, 0.0, DSU_MAX_AREA_SHRINK);
        if (cap <= 0.002) return start;

        const double minAllowedArea = start.area * (1.0 - cap);
        LayoutResult best = start;

        vector<double> steps = { 0.030, 0.022, 0.016, 0.011, 0.007, 0.004, 0.002 };
        int acceptCount = 0;
        for (double step : steps) {
            bool improved = true;
            int pass = 0;
            while (improved && pass++ < DSU_MAX_PASSES) {
                improved = false;
                for (int mode = 0; mode < 3; ++mode) {
                    bool cx = (mode == 0 || mode == 2);
                    bool cy = (mode == 1 || mode == 2);
                    double newW = cx ? best.W * (1.0 - step) : best.W;
                    double newH = cy ? best.H * (1.0 - step) : best.H;
                    newW = clampD(newW, 1.0, design.maxOutlineW);
                    newH = clampD(newH, 1.0, design.maxOutlineH);
                    if (newW * newH < minAllowedArea - EPS) continue;

                    LayoutResult cand = applyDSUScaleCandidate(design, best, newW, newH, cx, cy);
                    if (!dsuAcceptable(design, cand, start, minAllowedArea)) continue;
                    if (cand.area < best.area - 1.0 || betterLayout(cand, best)) {
                        best = std::move(cand);
                        improved = true;
                        ++acceptCount;
                    }
                }
            }
        }

        cerr << fixed << setprecision(3)
            << "[DSUPost] deadspace=" << deadspace
            << " cap=" << cap
            << " accept=" << acceptCount
            << " area=" << start.area << "->" << best.area
            << " W/H=" << start.W << "x" << start.H << "->" << best.W << "x" << best.H
            << " hpwl=" << start.hpwl << "->" << best.hpwl
            << " routeGap=" << start.routePenalty << "->" << best.routePenalty
            << " gapPart=" << start.routeGapPenaltyPart << "->" << best.routeGapPenaltyPart
            << " portPart=" << start.routePortPenaltyPart << "->" << best.routePortPenaltyPart
            << " maxGapMiss=" << start.routeMaxGapMiss << "->" << best.routeMaxGapMiss
            << " maxPortMiss=" << start.routeMaxPortMiss << "->" << best.routeMaxPortMiss
            << " violPairs=" << start.routeViolPairs << "->" << best.routeViolPairs
            << "\n";
        return best;
    }

    static void commitLayout(Design& design, const LayoutResult& best) {
        design.outlineW = clampD(best.W, 1.0, design.maxOutlineW);
        design.outlineH = clampD(best.H, 1.0, design.maxOutlineH);
        design.blocks.clear();
        design.blocks.reserve(design.blockSpecs.size());
        for (int i = 0; i < static_cast<int>(design.blockSpecs.size()); ++i) {
            BlockInst b;
            b.spec = design.blockSpecs[i];
            if (i < static_cast<int>(best.rects.size())) b.rect = best.rects[i];
            else b.rect = makeShape(design.blockSpecs[i], aspectMid(design.blockSpecs[i]));
            b.rect.x = clampD(b.rect.x, 0.0, max(0.0, design.outlineW - b.rect.w));
            b.rect.y = clampD(b.rect.y, 0.0, max(0.0, design.outlineH - b.rect.h));
            b.ftUsed = 0.0;
            b.ftOverflowArea = 0.0;
            design.blocks.push_back(b);
        }
        design.blockNameToIndex.clear();
        for (int i = 0; i < static_cast<int>(design.blocks.size()); ++i) {
            design.blockNameToIndex[design.blocks[i].spec.name] = i;
        }
    }

} // namespace

void Floorplanner::run(Design& design) {
    if (design.blockSpecs.empty()) {
        design.blocks.clear();
        return;
    }

    design.outlineW = design.maxOutlineW;
    design.outlineH = design.maxOutlineH;

    vector<vector<int>> orders = makeOrders(design);
    vector<ShapeState> shapes = makeShapeStates(design);

    LayoutResult best;
    bool have = false;
    int tried = 0;
    int packed = 0;

    const int nBlocks = static_cast<int>(design.blockSpecs.size());
    const int targetCandidates = max(1, nBlocks * nBlocks);
    const int maxCandidates = min(
        FAST_MAX_TOTAL_LAYOUT_CANDIDATES,
        max(targetCandidates, 2 * targetCandidates + 200)
    );

    int nEdge = 0, nHard = 0, nSoft = 0, nMovable = 0;
    for (const auto& spec : design.blockSpecs) {
        if (spec.type == BlockType::EDGE) ++nEdge;
        else {
            ++nMovable;
            if (spec.type == BlockType::HARD) ++nHard;
            else if (spec.type == BlockType::SOFT) ++nSoft;
        }
    }
    long long totalNets = 0;
    int maxNet = 0;
    int connCount = 0;
    if (!design.connections.empty()) {
        connCount = static_cast<int>(design.connections.size());
        for (const auto& c : design.connections) {
            totalNets += max(0, c.netCount);
            maxNet = max(maxNet, max(0, c.netCount));
        }
    }
    else {
        int nn = static_cast<int>(design.connMatrix.size());
        for (int i = 0; i < nn; ++i) {
            for (int j = i + 1; j < static_cast<int>(design.connMatrix[i].size()); ++j) {
                int nets = totalConnBetween(design, i, j);
                if (nets <= 0) continue;
                ++connCount;
                totalNets += nets;
                maxNet = max(maxNet, nets);
            }
        }
    }

    int strictTried = 0, strictPacked = 0, strictLegal = 0, strictEdgeOK = 0;
    int looseTried = 0, loosePacked = 0, looseLegal = 0, looseEdgeOK = 0;
    int bestUpdates = 0;
    if (FAST_VERBOSE_LOG) {
        cerr << fixed << setprecision(3)
            << "[FastSourcePack/Config] blocks=" << nBlocks
            << " movable=" << nMovable
            << " edge=" << nEdge
            << " hard=" << nHard
            << " soft=" << nSoft
            << " conn=" << connCount
            << " totalNets=" << totalNets
            << " maxNet=" << maxNet
            << " orders=" << orders.size()
            << " shapes=" << shapes.size()
            << " n2Target=" << targetCandidates
            << " maxCap=" << maxCandidates
            << " maxOutline=" << design.maxOutlineW << "x" << design.maxOutlineH
            << " blockArea=" << totalNominalArea(design)
            << "\n";
        cerr << fixed << setprecision(3)
            << "[FastSourcePack/GapPolicy] density=" << ROUTE_DENSITY
            << " fullMaxGap=" << maxSingleNetRequired(design)
            << " snap=" << sliverSnapThresholdFast(design)
            << " splitScale=" << SPLIT_AWARE_MIN_SCALE_FAST << ".." << SPLIT_AWARE_MAX_SCALE_FAST
            << " endpointGuardScale=" << ENDPOINT_GUARD_SCALE_FAST
            << " endpointGuardCap=" << ENDPOINT_GUARD_CAP_FAST
            << " dsu=" << (ENABLE_DSU_POST_COMPACTION ? "ON" : "OFF")
            << " dsuMaxShrink=" << DSU_MAX_AREA_SHRINK
            << "\n";
    }

    auto tryCandidate = [&](const ShapeState& st, const vector<int>& order, double W, double H, bool strictEdge) {
        ++tried;
        if (strictEdge) ++strictTried; else ++looseTried;
        LayoutResult cur;
        if (!tryExplicitWH(design, order, st, W, H, strictEdge, cur)) return;
        ++packed;
        if (strictEdge) {
            ++strictPacked;
            if (cur.legal) ++strictLegal;
            if (cur.strictEdgeLegal) ++strictEdgeOK;
        }
        else {
            ++loosePacked;
            if (cur.legal) ++looseLegal;
            if (cur.strictEdgeLegal) ++looseEdgeOK;
        }
        if (!have || betterLayout(cur, best)) {
            best = std::move(cur);
            have = true;
            ++bestUpdates;
        }
        };

    auto runPass = [&](bool strictEdge, int stopAfterTried) {
        for (const ShapeState& st : shapes) {
            vector<double> widths = makeWidthTrials(design, st);
            for (const vector<int>& order : orders) {
                for (double W : widths) {
                    vector<double> heights = makeHeightTrials(design, st, W);
                    for (double H : heights) {
                        if (tried >= stopAfterTried && have && best.legal) return;
                        if (tried >= maxCandidates && have) return;
                        tryCandidate(st, order, W, H, strictEdge);
                    }
                }
            }
        }
        };

    auto printPassSummary = [&](const string& name, int triedBefore, int packedBefore, int legalBefore) {
        if (!FAST_VERBOSE_LOG) return;
        int legalNow = strictLegal + looseLegal;
        cerr << fixed << setprecision(3)
            << "[FastSourcePack/Pass] name=" << name
            << " triedDelta=" << (tried - triedBefore)
            << " packedDelta=" << (packed - packedBefore)
            << " legalDelta=" << (legalNow - legalBefore)
            << " totalTried=" << tried
            << " totalPacked=" << packed
            << " strictPacked=" << strictPacked
            << " loosePacked=" << loosePacked
            << " strictLegal=" << strictLegal
            << " looseLegal=" << looseLegal
            << " strictEdgeOK=" << strictEdgeOK
            << " looseEdgeOK=" << looseEdgeOK
            << " bestUpdates=" << bestUpdates
            << " have=" << (have ? "Y" : "N");
        if (have) {
            cerr << " bestLegal=" << (best.legal ? "Y" : "N")
                << " bestEdgeLegal=" << (best.strictEdgeLegal ? "Y" : "N")
                << " bestArea=" << best.area
                << " bestW/H=" << best.W << "x" << best.H
                << " bestHpwl=" << best.hpwl
                << " bestRouteGap=" << best.routePenalty
                << " gapPart=" << best.routeGapPenaltyPart
                << " portPart=" << best.routePortPenaltyPart
                << " violPairs=" << best.routeViolPairs << "/" << best.routeConnectedPairs;
        }
        cerr << "\n";
        };

    // Main pass: exactly the desired behavior ¡X at least n^2 high-level layout
    // candidates when a legal solution is available early, with a hard cap to
    // avoid runtime explosion.  Each candidate is one explicit W/H coordinate pack;
    // no repeated binary search in the hot loop.
    int passTried0 = tried, passPacked0 = packed, passLegal0 = strictLegal + looseLegal;
    runPass(true, targetCandidates);
    printPassSummary("strict-edge", passTried0, passPacked0, passLegal0);

    // If strict EDGE zones prevented legal packing, use permissive EDGE packing
    // only for additional recovery candidates, still under the global cap.
    if (!have || !best.legal) {
        passTried0 = tried; passPacked0 = packed; passLegal0 = strictLegal + looseLegal;
        runPass(false, maxCandidates);
        printPassSummary("permissive-edge-recovery", passTried0, passPacked0, passLegal0);
    }

    // Optional local height refinement around the selected layout only.  This keeps
    // the n^2 exploration cheap while recovering some area from the best candidate.
    if (have && best.legal) {
        LayoutResult beforeRefine = best;
        LayoutResult refined = best;
        double lo = minHeightBound(design, shapes.front());
        double hi = best.H;
        int refineTried = 0, refineSuccess = 0, refineImprove = 0;
        for (int it = 0; it < FAST_HEIGHT_BISECT; ++it) {
            double mid = 0.5 * (lo + hi);
            LayoutResult cur;
            // Reuse the first robust order/state as a conservative local shrink is
            // unsafe because we no longer know which state produced best.  Therefore
            // refine only by accepting if explicit packing succeeds and improves.
            bool accepted = false;
            for (const ShapeState& st : shapes) {
                if (accepted) break;
                for (const vector<int>& order : orders) {
                    ++refineTried;
                    if (tryExplicitWH(design, order, st, best.W, mid, best.strictEdgeLegal, cur) && cur.legal) {
                        ++refineSuccess;
                        if (betterLayout(cur, refined)) {
                            refined = std::move(cur);
                            hi = mid;
                            ++refineImprove;
                        }
                        accepted = true;
                        break;
                    }
                }
            }
            if (!accepted) lo = mid;
        }
        if (betterLayout(refined, best)) best = std::move(refined);
        if (FAST_VERBOSE_LOG) {
            cerr << fixed << setprecision(3)
                << "[HeightRefine] tried=" << refineTried
                << " success=" << refineSuccess
                << " improve=" << refineImprove
                << " area=" << beforeRefine.area << "->" << best.area
                << " H=" << beforeRefine.H << "->" << best.H
                << " hpwl=" << beforeRefine.hpwl << "->" << best.hpwl
                << " routeGap=" << beforeRefine.routePenalty << "->" << best.routePenalty
                << "\n";
        }
    }

    if (!have) {
        best = fallbackShelf(design);
        if (FAST_VERBOSE_LOG) {
            cerr << fixed << setprecision(3)
                << "[FastSourcePack/Fallback] used=Y"
                << " legal=" << (best.legal ? "Y" : "N")
                << " area=" << best.area
                << " W/H=" << best.W << "x" << best.H
                << " hpwl=" << best.hpwl
                << " routeGap=" << best.routePenalty
                << "\n";
        }
    }

    LayoutResult preDSU = best;
    // Phase 2: bounded DSU-style compaction.  Phase 1 used relaxed requiredGap;
    // this post pass reclaims deadspace without adding any candidate/SA cost.
    if (best.legal) best = dsuPostCompaction(design, best);

    if (FAST_VERBOSE_LOG) {
        cerr << fixed << setprecision(3)
            << "[FastSourcePack/Selected] preDSUArea=" << preDSU.area
            << " postDSUArea=" << best.area
            << " preW/H=" << preDSU.W << "x" << preDSU.H
            << " postW/H=" << best.W << "x" << best.H
            << " preRouteGap=" << preDSU.routePenalty
            << " postRouteGap=" << best.routePenalty
            << " preHpwl=" << preDSU.hpwl
            << " postHpwl=" << best.hpwl
            << "\n";
    }

    commitLayout(design, best);

    cerr << fixed << setprecision(3)
        << "[FastSourcePack/N2] n2Target=" << targetCandidates
        << " tried=" << tried
        << " packed=" << packed
        << " legal=" << (best.legal ? "Y" : "N")
        << " edgeLegal=" << (best.strictEdgeLegal ? "Y" : "N")
        << " area=" << best.area
        << " W/H=" << best.W << "x" << best.H
        << " hpwl=" << best.hpwl
        << " routeGap=" << best.routePenalty
        << " gapPart=" << best.routeGapPenaltyPart
        << " portPart=" << best.routePortPenaltyPart
        << " maxGapMiss=" << best.routeMaxGapMiss
        << " maxPortMiss=" << best.routeMaxPortMiss
        << " routeViolPairs=" << best.routeViolPairs << "/" << best.routeConnectedPairs
        << " routeXY=" << best.routeXInterfaces << "/" << best.routeYInterfaces
        << " overlap=" << best.overlap
        << " edgeViol=" << best.edgeViol
        << " outlineViol=" << best.outlineViol
        << " strictTried/Packed/Legal=" << strictTried << "/" << strictPacked << "/" << strictLegal
        << " looseTried/Packed/Legal=" << looseTried << "/" << loosePacked << "/" << looseLegal
        << " bestUpdates=" << bestUpdates
        << " maxTriedCap=" << maxCandidates
        << "\n";
}

// --------------------------------------------------------------------------
// Compatibility methods for the existing Floorplanner.hpp interface.
// --------------------------------------------------------------------------

Rect Floorplanner::makeInitialShape(const BlockSpec& spec) const {
    return makeShape(spec, aspectMid(spec));
}

void Floorplanner::initBlockShapes(Design& design) {
    design.blocks.clear();
    design.blocks.reserve(design.blockSpecs.size());
    for (const auto& spec : design.blockSpecs) {
        BlockInst b;
        b.spec = spec;
        b.rect = makeInitialShape(spec);
        b.ftUsed = 0.0;
        b.ftOverflowArea = 0.0;
        design.blocks.push_back(b);
    }
}

Rect Floorplanner::placeByLocation(const Rect& shape, const string& loc, double W, double H) const {
    EdgeRule r = parseRule(loc);
    Rect out = shape;
    double len = sideLen(shape, r.side);
    auto zb = zoneBounds(r, W, H);
    double axis = clampD(zoneCenter(r, W, H) - 0.5 * len, zb.first, zb.second - len);
    setEdgeAxis(out, r, axis, W, H);
    return out;
}

bool Floorplanner::insideOutline(const Rect& r, double W, double H) const {
    return inside(r, W, H);
}

bool Floorplanner::overlapsPlaced(const Rect& r, const vector<BlockInst>& blocks, const vector<bool>& placed) const {
    for (int i = 0; i < static_cast<int>(blocks.size()); ++i) {
        if (!placed[i]) continue;
        if (ovArea(r, blocks[i].rect) > EPS) return true;
    }
    return false;
}

double Floorplanner::connectionWeightToPlaced(int blockId, const Design& design, const vector<bool>& placed, const Rect& cand) const {
    double s = 0.0;
    for (int j = 0; j < static_cast<int>(design.blocks.size()); ++j) {
        if (!placed[j]) continue;
        int nets = totalConnBetween(design, blockId, j);
        if (nets <= 0) continue;
        s += static_cast<double>(nets) *
            (fabs(rectCx(cand) - rectCx(design.blocks[j].rect)) + fabs(rectCy(cand) - rectCy(design.blocks[j].rect)));
    }
    return s;
}

vector<double> Floorplanner::collectCandidateXs(const Design& design, double w) const {
    vector<double> xs = { 0.0 };
    for (const auto& b : design.blocks) {
        xs.push_back(b.rect.x);
        xs.push_back(rectRight(b.rect));
        xs.push_back(max(0.0, b.rect.x - w));
        xs.push_back(max(0.0, rectRight(b.rect) - w));
    }
    xs.push_back(max(0.0, design.outlineW - w));
    sort(xs.begin(), xs.end());
    xs.erase(unique(xs.begin(), xs.end(), [](double a, double b) { return fabs(a - b) < 1e-3; }), xs.end());
    return xs;
}

vector<double> Floorplanner::collectCandidateYs(const Design& design, double h) const {
    vector<double> ys = { 0.0 };
    for (const auto& b : design.blocks) {
        ys.push_back(b.rect.y);
        ys.push_back(rectTop(b.rect));
        ys.push_back(max(0.0, b.rect.y - h));
        ys.push_back(max(0.0, rectTop(b.rect) - h));
    }
    ys.push_back(max(0.0, design.outlineH - h));
    sort(ys.begin(), ys.end());
    ys.erase(unique(ys.begin(), ys.end(), [](double a, double b) { return fabs(a - b) < 1e-3; }), ys.end());
    return ys;
}

void Floorplanner::placeEdgeBlocks(Design& design) {
    if (design.blocks.size() != design.blockSpecs.size()) initBlockShapes(design);
    ShapeState st;
    st.ratio.assign(design.blockSpecs.size(), 1.0);
    for (int i = 0; i < static_cast<int>(design.blockSpecs.size()); ++i) st.ratio[i] = aspectMid(design.blockSpecs[i]);
    vector<Rect> shapes = makeShapes(design, st);
    vector<Rect> rects, obstacles;
    placeEdgesFast(design, shapes, design.outlineW, design.outlineH, rects, obstacles, false);
    for (int i = 0; i < static_cast<int>(design.blocks.size()) && i < static_cast<int>(rects.size()); ++i) {
        if (design.blockSpecs[i].type == BlockType::EDGE) design.blocks[i].rect = rects[i];
    }
}

void Floorplanner::placeRemainingBlocksGreedy(Design& design) {
    (void)design;
}
